require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"

require "user.lsp"

require "user.config.alpha"
require "user.config.autopairs"
require "user.config.bufferline"
require "user.config.comment"
require "user.config.copilot"
require "user.config.gitsigns"
require "user.config.impatient"
require "user.config.indentline"
require "user.config.lualine"
require "user.config.noice"
require "user.config.nvim-tree"
require "user.config.project"
require "user.config.scope"
require "user.config.telescope"
require "user.config.toggleterm"
require "user.config.treesitter"
require "user.config.whichkey"

